development:
  adapter: postgresql
  database: microlearning_development
test:
  adapter: 'postgresql'
  database: microlearning_test
production:
  adapter: 'postgresql'
  database: microlearning_production
