development:
  adapter: postgresql
  database: microlearning_development
test:
  adapter: 'postgresql'
  database: microlearning_test
production:
  adapter: 'postgresql'
  encoding: 'unicode'
  host: <%= ENV['DATABASE_HOST'] %>
  database: d1rd8mgir50ja3
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
